export const CHANHE_SINGET_LIST = 'singer/CHANHE_SINGET_LIST';
export const CHANGE_ENTER_LOADING = 'singer/CHANGE_ENTER_LOADING';
export const CHANHE_PULLUP_LOADING = 'singer/CHANHE_PULLUP_LOADING';
export const CHANHE_PULLDOWN_LOADING = 'singer/CHANHE_PULLDOWN_LOADING';
export const CHANGE_PAGE_COUNT = 'singer/CHANGE_PAGE_COUNT';